# Generated by Django 3.2.10 on 2021-12-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='countrycode',
        ),
    ]
